---
commitizen:
  name: cz_conventional_commits
  tag_format: $version
  update_changelog_on_bump: true
  version: 0.0.0
  version_files:
    - Cargo.toml
    - packages/http-canister-client/package.json:version
